# Generated by Django 3.2.9 on 2022-06-22 23:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnet_identidad', models.CharField(max_length=11, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('edad', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('especialidad', models.CharField(max_length=150)),
                ('categoria_cientifica', models.CharField(choices=[('Ninguna', 'Ninguna'), ('Master', 'Master'), ('Doctor', 'Doctor')], help_text='Valor por defecto Ninguna', max_length=7)),
                ('categoria_docente', models.CharField(choices=[('Asistente', 'Asistente'), ('Ausiliar', 'Ausiliar'), ('Instructor', 'Instructor'), ('Titular', 'Titular')], help_text='Valor por defecto Titular', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
